### ISSUE TITLE
[SUGGEST] Readme 작성

### ISSUE THREAD

**Issue by heesunc** [Controller-Team/UNDEADER#3]
## Description
프로젝트 개요를 알 수 있는 Readme를 작성했으면 좋겠습니다

**Comment by Suldangoo** [comment]
좋습니다! Readme엔 어떤 내용을 넣으면 좋을까요?

**Comment by kangtoe** [comment]
프로젝트에서 사용한 기술들을 포함하면 좋을 것 같습니다!

**Comment by kangtoe** [comment]
> 프로젝트에서 사용한 기술들을 포함하면 좋을 것 같습니다!

현재까지 개발된 사항이 아니라도 향후 개발 확정된 사항(예-서버 간 데이터 연동 등)도 기술하면 더욱 좋겠습니다
