### ISSUE TITLE
[FIX] 닷지 중 충돌 무시 기능

### ISSUE THREAD

**Issue by kangtoe** [Controller-Team/UNDEADER#34]
## Description
플레이어 캐릭터의 닷지 기능 사용 시 좀비에 막히지 않도록 수정

## TODO

- [x] 닷지 중 Pawn과의 충돌처리를 수행하지 않도록 수정

## Reference

![3037479136_preview_Honeycam-2023-09-18-14-11-22](https://github.com/user-attachments/assets/c37a34d1-6e6c-42c3-bfe7-b77b57d283bb)
다만 위 이미지와는 다른 환경으로, 본 프로젝트의 3D 공간에서 대시 중 장애물과 충돌 시 어떻게 처리해야 할지 모호한 부분이 있습니다.

## Additional context

개발 중 추가적인 특기 사항 발생 시 작성하겠습니다.

**Comment by Suldangoo** [comment]
벽이나 장애물에 대해서는 현재 대시의 판정을 유지하고 (가로막힘)
좀비에 대해서는 콜라이더를 무시하고 통과하나 (통과됨)

도착한 지점에 좀비와 모델이 겹칠 경우만 주의하면 좋을 것 같습니다.
우선 그냥 무시하고 개발해보고, 콜라이더가 켜졌을 때 알아서 잘 밀려나면 그대로 해도 좋을 것 같습니다.
만약 예상한 결과가 나오지 않고 버그로 판정되는 현상이 일어나면 별도의 처리를 해야할 것 같습니다.

**Comment by kangtoe** [comment]
@Suldangoo 넵 감사합니다
현재 말씀하신 대로 DodgeFix 브랜치에서 개발 중입니다
한번 중간 점검 해주셔도 좋을 것 같습니다
